### ISSUE TITLE
Morning Peer-to-peer code review

### ISSUE THREAD

**Issue by Sahar-AbdelSamad** [carloshs1994/easyscience#1]
##To Highlight ##
- Your project look very good
- The Style of the page is original
- The project is responsive

##Suggestions##
- You can add the logo in the footer
- In the third section of the home page, we think it would be better if you add more descriptions
- It is better if you make the hamburger button dynamic (it can open and close when we press it)

**Comment by carloshs1994** [comment]
<img src="https://media3.giphy.com/media/8UF0EXzsc0Ckg/giphy.gif"/>
